# Dependency selection is shared by the native build and configuration tests.
function(nccl_cp_select_architectures nvcc)
  if(DEFINED CMAKE_CUDA_ARCHITECTURES AND NOT CMAKE_CUDA_ARCHITECTURES STREQUAL "")
    return()
  endif()
  if(DEFINED ENV{CUDAARCHS} AND NOT "$ENV{CUDAARCHS}" STREQUAL "")
    set(CMAKE_CUDA_ARCHITECTURES "$ENV{CUDAARCHS}" CACHE STRING "CUDA architecture targets" FORCE)
    set(CMAKE_CUDA_ARCHITECTURES "$ENV{CUDAARCHS}" PARENT_SCOPE)
    return()
  endif()
  execute_process(COMMAND "${nvcc}" --list-gpu-code
    RESULT_VARIABLE _result OUTPUT_VARIABLE _codes ERROR_VARIABLE _error)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Cannot query CUDA architecture targets from ${nvcc}: ${_error}")
  endif()
  string(REGEX MATCHALL "sm_[0-9]+[a-z]*" _supported "${_codes}")
  set(_targets "")
  foreach(_arch 80 90 100 110 120)
    if("sm_${_arch}" IN_LIST _supported)
      list(APPEND _targets "${_arch}")
    endif()
  endforeach()
  if(NOT _targets)
    message(FATAL_ERROR "NVCC supports none of the default CP architectures (80, 90, 100, 110, 120)")
  endif()
  set(CMAKE_CUDA_ARCHITECTURES "${_targets}" CACHE STRING "CUDA architecture targets" FORCE)
  set(CMAKE_CUDA_ARCHITECTURES "${_targets}" PARENT_SCOPE)
endfunction()

function(nccl_cp_find_nccl project_root)
  if(DEFINED ENV{NCCL_HOME} AND NOT "$ENV{NCCL_HOME}" STREQUAL "")
    set(_default "$ENV{NCCL_HOME}")
  elseif(DEFINED ENV{NCCL_CP_NCCL_HOME} AND NOT "$ENV{NCCL_CP_NCCL_HOME}" STREQUAL "")
    set(_default "$ENV{NCCL_CP_NCCL_HOME}")
  elseif(EXISTS "${project_root}/../nccl_ep/CMakeLists.txt")
    set(_default "${project_root}/../third_party/nccl/build")
  else()
    set(_default "${project_root}/third_party/nccl/build")
  endif()
  set(NCCL_HOME "${_default}" CACHE PATH "NCCL root containing include/nccl.h and lib or lib64")
  if(NOT EXISTS "${NCCL_HOME}/include/nccl.h")
    message(FATAL_ERROR "No include/nccl.h under NCCL_HOME=${NCCL_HOME}. Run make nccl-submodule or select an existing NCCL build.")
  endif()
  # Do not reuse a cached library from a previously selected NCCL_HOME.
  set(_library "_library-NOTFOUND")
  find_library(_library NAMES nccl PATHS "${NCCL_HOME}/lib" "${NCCL_HOME}/lib64"
    NO_DEFAULT_PATH NO_CACHE)
  if(NOT _library)
    file(GLOB _libraries "${NCCL_HOME}/lib/libnccl.so.*" "${NCCL_HOME}/lib64/libnccl.so.*")
    list(SORT _libraries COMPARE NATURAL ORDER DESCENDING)
    if(_libraries)
      list(GET _libraries 0 _library)
    endif()
  endif()
  if(NOT _library)
    message(FATAL_ERROR "No libnccl.so was found under NCCL_HOME=${NCCL_HOME}")
  endif()
  set(NCCL_CP_NCCL_LIBRARY "${_library}" PARENT_SCOPE)
endfunction()
